### Array and Matrix  

In [1]:
import numpy as np
import pandas as pd

In [2]:
%timeit [4 + i for i in range(10000)]

The slowest run took 6.77 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 687 µs per loop


In [3]:
%timeit (4 + np.arange(10000))

The slowest run took 642.53 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 11.9 µs per loop


In [4]:
# Array is 1 Dimensional 
np.array([1,2,3])

array([1, 2, 3])

In [5]:
# Matrix is 2 Dimensional 
var = np.array([[1,2,3,1],[4,5,6,4],[7,8,9,7]])
print('matrix is \n', var)
print('\n')
print(var.T)

matrix is 
 [[1 2 3 1]
 [4 5 6 4]
 [7 8 9 7]]


[[1 4 7]
 [2 5 8]
 [3 6 9]
 [1 4 7]]


In [6]:
%timeit [i**i for i in range(1,500,20)]  # normal range 

10000 loops, best of 3: 56.5 µs per loop


In [7]:
np.arange(0,10).reshape(5,2).shape # python range 

(5, 2)

In [8]:
%timeit [i**i for i in np.arange(1,500,20)]
 

The slowest run took 8.13 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 7.16 µs per loop


In [9]:
print(range(0,10,2))   # Range only stores starting ending 
print(np.arange(0,10,2))  # Numpy stores all the values , starting is inclusive , end is exclusive

range(0, 10, 2)
[0 2 4 6 8]


In [10]:
np.linspace(0,10,5)   # both starting and ending are inclusive 

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
np.linspace(0,20,21).reshape(7,3)  # using the reshape we convert to matrix 

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.]])

In [12]:
print(np.ones((5,3)))  # this is right 
print('\n')
print(np.ones([5,3]))   # this is also correct 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
print(np.eye((5))) # this is correct 
print('\n')   
print(np.eye(5))   # this is also correct 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
print(np.arange(0,5) + np.arange(1,6) )    # for addition elements should be same 

print(np.arange(0,4)* np.arange(0,4))    # for multiplication elements should be same     

[1 3 5 7 9]
[0 1 4 9]


In [16]:
a = np.arange(0,10,2)
print(a)
np.sqrt(a)

[0 2 4 6 8]


array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712])

In [17]:
a=np.arange(1,20,2).reshape(5,2)
b=np.linspace(0,20,2).reshape(2,1)
c = np.linspace(0,9,10).reshape(5,2)
print(a)
print('\n')
print(f'{b} \n')
print(c)

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]


[[ 0.]
 [20.]] 

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


### Matrix Multiplication

Matrix Multiplication
The Numpy matmul() function is used to return the matrix product of 2 arrays. Here is how it works

1) 2-D arrays, it returns normal product

2) Dimensions > 2, the product is treated as a stack of matrix

3) 1-D array is first promoted to a matrix, and then the product is calculated

In [18]:
print(a * c)
print(np.dot(a,b))
print(a @ b)    #  @ is called mat multi plication 
np.matmul(a,b)  # mat mul and dot are same for 2d arrays but for 3d they are different 


[[  0.   3.]
 [ 10.  21.]
 [ 36.  55.]
 [ 78. 105.]
 [136. 171.]]
[[ 60.]
 [140.]
 [220.]
 [300.]
 [380.]]
[[ 60.]
 [140.]
 [220.]
 [300.]
 [380.]]


array([[ 60.],
       [140.],
       [220.],
       [300.],
       [380.]])

In [1]:
a = np.array(([1,2,3],[4,5,6],[7,8,9]))
b = np.array([1,2,3]).reshape(3,1)



NameError: ignored

In [20]:
a = [[1,0],[0,1]] 
b = [1,2] 
np.matmul(a,b)


array([1, 2])

In [21]:
a = [[1,0],[0,1]] 
b = [[4,1],[2,2]] 

print(np.matmul(a,b))

[[4 1]
 [2 2]]


In [22]:
import numpy as np

a = np.array([1, 3, 5, 7, 9,11])
a
np.reshape(a,(6,1))

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]])

In [23]:
c= a = [[1,0],[0,1]] 
b = [1,2] 
c=np.matmul(a,b)
print(c.shape)
d=c.reshape(2,1)
print(d.shape)
print(type(c))
print(type(d))

(2,)
(2, 1)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [24]:
a = np.arange(8).reshape(2,2,2) 
b = np.arange(4).reshape(2,2) 
c=np.matmul(a,b)
c.shape
print(c)

[[[ 2  3]
  [ 6 11]]

 [[10 19]
  [14 27]]]


In [25]:
a = [1,2]
b=[2,1]
np.matmul(a,b)

4

In [ ]:
import numpy as np
a = np.ones([9, 5, 7, 4])
c = np.ones([9, 5, 4, 3])
np.dot(a, c).shape


In [27]:
# a 3x2 matrix
A = np.array([[8, 2, 2],
             [1, 0, 3]]) 

# a 2x3 matrix
B = np.array([[1, 3],
             [5, 0],
             [9, 6]])

# dot product should return a 2x2 product
C = np.dot(A, B)
C

array([[36, 36],
       [28, 21]])

In [28]:
D=B.reshape(2,3)

In [29]:
E=A * D
E

array([[ 8,  6, 10],
       [ 0,  0, 18]])

### Matmul vs Dot product 
[Follow this Link](https://likegeeks.com/numpy-matrix-multiplication/)

In [30]:
np.random.seed(42)

A  = np.random.randint(0, 10, size=(3,3,2))

B  = np.random.randint(0, 10, size=(3,2,4))

print("A:\n{}, shape={}\nB:\n{}, shape={}".format(A, A.shape,B, B.shape))

A:
[[[6 3]
  [7 4]
  [6 9]]

 [[2 6]
  [7 4]
  [3 7]]

 [[7 2]
  [5 4]
  [1 7]]], shape=(3, 3, 2)
B:
[[[5 1 4 0]
  [9 5 8 0]]

 [[9 2 6 3]
  [8 2 4 2]]

 [[6 4 8 6]
  [1 3 8 1]]], shape=(3, 2, 4)


In [31]:
C = np.matmul(A,B)

print("Product C:\n{}, shape={}".format(C, C.shape))

Product C:
[[[ 57  21  48   0]
  [ 71  27  60   0]
  [111  51  96   0]]

 [[ 66  16  36  18]
  [ 95  22  58  29]
  [ 83  20  46  23]]

 [[ 44  34  72  44]
  [ 34  32  72  34]
  [ 13  25  64  13]]], shape=(3, 3, 4)


In [32]:
np.random.seed(42)

A  = np.random.randint(0, 10, size=(2,3,2))

B  = np.random.randint(0, 10, size=(3,2,4))

print("A:\n{}, shape={}\nB:\n{}, shape={}".format(A, A.shape,B, B.shape))

A:
[[[6 3]
  [7 4]
  [6 9]]

 [[2 6]
  [7 4]
  [3 7]]], shape=(2, 3, 2)
B:
[[[7 2 5 4]
  [1 7 5 1]]

 [[4 0 9 5]
  [8 0 9 2]]

 [[6 3 8 2]
  [4 2 6 4]]], shape=(3, 2, 4)


In [33]:
C = np.dot(A,B)

print("np.dot(A,B) =\n{}, shape={}".format(C, C.shape))


np.dot(A,B) =
[[[[ 45  33  45  27]
   [ 48   0  81  36]
   [ 48  24  66  24]]

  [[ 53  42  55  32]
   [ 60   0  99  43]
   [ 58  29  80  30]]

  [[ 51  75  75  33]
   [ 96   0 135  48]
   [ 72  36 102  48]]]


 [[[ 20  46  40  14]
   [ 56   0  72  22]
   [ 36  18  52  28]]

  [[ 53  42  55  32]
   [ 60   0  99  43]
   [ 58  29  80  30]]

  [[ 28  55  50  19]
   [ 68   0  90  29]
   [ 46  23  66  34]]]], shape=(2, 3, 3, 4)


In [34]:
li=[1,2,3,3,3,3,4,4,4,4]   # unique works for array and the syntax is np.unique(array)
np.unique(np.array(li))

array([1, 2, 3, 4])

In [35]:
print(np.random.rand(3,2)) 
print('\n \n')   # Generating random numbers between 0 and 1 uniformly distributed 
print(np.random.randn(3,2))


[[0.45049925 0.01326496]
 [0.94220176 0.56328822]
 [0.3854165  0.01596625]]

 

[[-0.74907652 -0.77838201]
 [ 0.94884286  1.58085059]
 [-0.36817094  0.37556463]]


In [36]:
np.random.rand(3,2).mean()     # using the mean , std , min and ma xe can find the different descriptive statistics 

0.4215759951430635

In [37]:
np.random.randn(3,2).std()

1.1159508277836403

In [38]:
np.random.rand(3,2).min()

0.5208342600258237

### Assignment of Matrices 

In [5]:
import numpy as np
(np.random.randn(10))

(10,)

In [40]:
a=np.random.rand(10)
a[1]   # indexing with [] brackets 

0.6510770255019445

In [41]:
a[1]

0.6510770255019445

In [42]:
a[1:6:2]

array([0.65107703, 0.85003858, 0.09541012])

In [43]:
a[np.arange(0,10,3)]  # This gives us value of a based on index location given by arange

array([0.92630088, 0.85003858, 0.37081825, 0.59129779])

In [44]:
mat =np.random.randn(5,2)
mat

array([[ 0.45788508, -1.68428738],
       [ 0.32684522, -0.08111895],
       [ 0.46779475,  0.73612235],
       [-0.77970188, -0.84389636],
       [-0.15053386, -0.96555767]])

In [45]:
mat[0:2,1:3]

array([[-1.68428738],
       [-0.08111895]])

In [46]:
np.arange(5).shape

(5,)

In [47]:
# To access elemnts of matrix we can use 
mat[1][1]  #  This will use 1st row and 1st column
mat[1,1]   # This is also correct to access element of matrix 

-0.0811189541586873

In [48]:
a=np.random.randn(6,5)
a

array([[ 0.15048908, -0.11342125,  2.63352822, -1.02509089, -0.78204783],
       [ 0.42394307,  0.8727051 ,  2.28722598,  1.6229205 ,  0.82373308],
       [ 0.29305925,  0.89663038, -0.61032202, -0.3161659 , -1.48242425],
       [-0.22884752,  0.96264129, -0.20969244, -0.77404293, -0.35977815],
       [ 0.72408325, -0.25576464,  0.8499212 , -1.31132423, -0.87030495],
       [-0.50664322, -1.30995069,  2.94366342, -1.0962658 ,  0.91488432]])

In [49]:
a[2:4,1:3]   # to access elements 

array([[ 0.89663038, -0.61032202],
       [ 0.96264129, -0.20969244]])

In [50]:
a[0,2:4]=4   # This is assignment of matrix 
a

array([[ 0.15048908, -0.11342125,  4.        ,  4.        , -0.78204783],
       [ 0.42394307,  0.8727051 ,  2.28722598,  1.6229205 ,  0.82373308],
       [ 0.29305925,  0.89663038, -0.61032202, -0.3161659 , -1.48242425],
       [-0.22884752,  0.96264129, -0.20969244, -0.77404293, -0.35977815],
       [ 0.72408325, -0.25576464,  0.8499212 , -1.31132423, -0.87030495],
       [-0.50664322, -1.30995069,  2.94366342, -1.0962658 ,  0.91488432]])

In [51]:
a[1][1:4]=3   # This is also assignment of matrix to some other value 
a

array([[ 0.15048908, -0.11342125,  4.        ,  4.        , -0.78204783],
       [ 0.42394307,  3.        ,  3.        ,  3.        ,  0.82373308],
       [ 0.29305925,  0.89663038, -0.61032202, -0.3161659 , -1.48242425],
       [-0.22884752,  0.96264129, -0.20969244, -0.77404293, -0.35977815],
       [ 0.72408325, -0.25576464,  0.8499212 , -1.31132423, -0.87030495],
       [-0.50664322, -1.30995069,  2.94366342, -1.0962658 ,  0.91488432]])

In [52]:
a[0][1:5]   # Accessing ar5ray elements 
a[1:3,2:4]
a[3:5][:,2:5]    # Accessing elements of array 

array([[-0.20969244, -0.77404293, -0.35977815],
       [ 0.8499212 , -1.31132423, -0.87030495]])

In [53]:
a

array([[ 0.15048908, -0.11342125,  4.        ,  4.        , -0.78204783],
       [ 0.42394307,  3.        ,  3.        ,  3.        ,  0.82373308],
       [ 0.29305925,  0.89663038, -0.61032202, -0.3161659 , -1.48242425],
       [-0.22884752,  0.96264129, -0.20969244, -0.77404293, -0.35977815],
       [ 0.72408325, -0.25576464,  0.8499212 , -1.31132423, -0.87030495],
       [-0.50664322, -1.30995069,  2.94366342, -1.0962658 ,  0.91488432]])

In [54]:
a[0,2:4]=[3,4]
a

array([[ 0.15048908, -0.11342125,  3.        ,  4.        , -0.78204783],
       [ 0.42394307,  3.        ,  3.        ,  3.        ,  0.82373308],
       [ 0.29305925,  0.89663038, -0.61032202, -0.3161659 , -1.48242425],
       [-0.22884752,  0.96264129, -0.20969244, -0.77404293, -0.35977815],
       [ 0.72408325, -0.25576464,  0.8499212 , -1.31132423, -0.87030495],
       [-0.50664322, -1.30995069,  2.94366342, -1.0962658 ,  0.91488432]])

In [55]:
a

array([[ 0.15048908, -0.11342125,  3.        ,  4.        , -0.78204783],
       [ 0.42394307,  3.        ,  3.        ,  3.        ,  0.82373308],
       [ 0.29305925,  0.89663038, -0.61032202, -0.3161659 , -1.48242425],
       [-0.22884752,  0.96264129, -0.20969244, -0.77404293, -0.35977815],
       [ 0.72408325, -0.25576464,  0.8499212 , -1.31132423, -0.87030495],
       [-0.50664322, -1.30995069,  2.94366342, -1.0962658 ,  0.91488432]])

In [56]:
a[::]=1
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [57]:
# why we use copy function 
A = np.linspace(0,12,10).reshape(5,2)
A

array([[ 0.        ,  1.33333333],
       [ 2.66666667,  4.        ],
       [ 5.33333333,  6.66666667],
       [ 8.        ,  9.33333333],
       [10.66666667, 12.        ]])

In [58]:
B=A[0:2][:2].copy()
B
# Lets assign all value of B as 1
B[:]=1
B

array([[1., 1.],
       [1., 1.]])

In [59]:
# Now the check the value of A , as B is subset of A , changing value of B has changed A also
# For this reason we use .copy to create a copy of B from A
A

array([[ 0.        ,  1.33333333],
       [ 2.66666667,  4.        ],
       [ 5.33333333,  6.66666667],
       [ 8.        ,  9.33333333],
       [10.66666667, 12.        ]])

### Saving and Loading Numpy arrays 

In [60]:
# Indexing and slicing using Booleans 

rand=np.random.randn(10)
print(rand)

print('')

A =rand >0
print(A)

B =rand[A]
print('')
B

[-0.66606062 -0.51378749  0.3013228  -1.45851692 -0.66273831 -0.14647281
 -0.84601702 -0.82248937  1.08672702  1.00498688]

[False False  True False False False False False  True  True]



array([0.3013228 , 1.08672702, 1.00498688])

In [61]:
# For a matrix Indexing with Boolean/Logical would return an array also

np.random.seed(42)
mat = np.random.randn(5,5)
print(mat)
print('')

B = mat >0 
print(B)
print('')
print(mat>0)
print('')

D=mat[B]
print(D)
print('')

D
print(np.reshape(D,(5,2)))   # This is one way of doing reshape
print('')
print(D.reshape(5,2))      # This is another way of doing reshape 

[[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]
 [-0.23413696  1.57921282  0.76743473 -0.46947439  0.54256004]
 [-0.46341769 -0.46572975  0.24196227 -1.91328024 -1.72491783]
 [-0.56228753 -1.01283112  0.31424733 -0.90802408 -1.4123037 ]
 [ 1.46564877 -0.2257763   0.0675282  -1.42474819 -0.54438272]]

[[ True False  True  True False]
 [False  True  True False  True]
 [False False  True False False]
 [False False  True False False]
 [ True False  True False False]]

[[ True False  True  True False]
 [False  True  True False  True]
 [False False  True False False]
 [False False  True False False]
 [ True False  True False False]]

[0.49671415 0.64768854 1.52302986 1.57921282 0.76743473 0.54256004
 0.24196227 0.31424733 1.46564877 0.0675282 ]

[[0.49671415 0.64768854]
 [1.52302986 1.57921282]
 [0.76743473 0.54256004]
 [0.24196227 0.31424733]
 [1.46564877 0.0675282 ]]

[[0.49671415 0.64768854]
 [1.52302986 1.57921282]
 [0.76743473 0.54256004]
 [0.24196227 0.31424733]
 [1.4656

In [62]:
A = np.random.randn(5,2)
print(A)

print('')

A[A<0] = -1     # This will do elemnt wise 
# operation for each elemtn of array to compare  
A



[[ 0.11092259 -1.15099358]
 [ 0.37569802 -0.60063869]
 [-0.29169375 -0.60170661]
 [ 1.85227818 -0.01349722]
 [-1.05771093  0.82254491]]



array([[ 0.11092259, -1.        ],
       [ 0.37569802, -1.        ],
       [-1.        , -1.        ],
       [ 1.85227818, -1.        ],
       [-1.        ,  0.82254491]])

In [63]:
#Saving numpy files - Single

np.save('A',np.random.randint(4,30,6))

In [64]:
# Loading numpy file - single 

np.load('A.npy')

array([ 5,  9, 25, 13,  7, 25])

In [65]:
# Saving multiple zipped files numpy
np.savez('Overall',A=np.random.randn(2,2),B=np.random.randn(3,2),C=np.random.randint(2,10,4))

In [66]:
# Loading multiple zipped files 
loaded=np.load('Overall.npz')

In [67]:
loaded['A']
print('')
np.load('Overall.npz')['C']

array([8, 6, 9, 3])

In [68]:
A=np.random.randn(5,4)

In [69]:
A.ndim,A.shape,A.size,A.dtype

(2, (5, 4), 20, dtype('float64'))

### Pandas 

In [70]:
import pandas as pd

In [71]:
# can be created from list
pd.Series([1,2,3,4])
# can be created from array
pd.Series(np.array([1,2,3,4]))

0    1
1    2
2    3
3    4
dtype: int64

In [72]:
# indexing happens same way as list and arrays 
# we can give labels to series
pd.Series([1,2,3,4],index=['a','b','c','d'])

a    1
b    2
c    3
d    4
dtype: int64

In [73]:
A=pd.Series([1,2,3,4],['a','b','c','d'])
A

a    1
b    2
c    3
d    4
dtype: int64

In [74]:
# can be accesed by index or by position 
A['c'] 
A[0]

1

In [75]:
# combining 2 series
pd.Series([1,2,3],['a','b','c']) + pd.Series([2,3,4],['b','c','d'])
# As a is not there in 2nd series and d is not in first series 2 + Nan is Nan, 
# because of this it returned Nan


a    NaN
b    4.0
c    6.0
d    NaN
dtype: float64

In [76]:
# Concatenation of 2 series results into Dataframe
pd.Series([1,2,3],index=('a','b','c'))

a    1
b    2
c    3
dtype: int64

In [77]:
A =pd.Series({'first':12,'second':23,'C':30},name='Series')
B =pd.Series({'fourth':12,'C':23,'D':30},name='Other')

In [78]:
pd.concat((A,B),axis=1, sort=True)   # We can concat the 2 series by row or column 

Series  Other
C         30.0   23.0
D          NaN   30.0
first     12.0    NaN
fourth     NaN   12.0
second    23.0    NaN

In [79]:
pd.DataFrame(np.arange(0,10).reshape(5,2),index=('a','b','c','d','e'),columns=('a','b'))   # Data frame thru np.arange

a  b
a  0  1
b  2  3
c  4  5
d  6  7
e  8  9

In [80]:
pd.DataFrame(np.linspace(1,12,12).reshape(4,3),index=(1,2,3,4),columns=(1,2,3))  # Dataframe can be created by np.linspace 

1     2     3
1   1.0   2.0   3.0
2   4.0   5.0   6.0
3   7.0   8.0   9.0
4  10.0  11.0  12.0

In [81]:
pd.DataFrame(np.random.rand(5,4),index=(1,2,3,4,5),columns=('a','b','c','d'))# Dataframe thru np.random.rand ....creates between 0 and 1 

a         b         c         d
1  0.382927  0.971712  0.848914  0.721730
2  0.235985  0.256068  0.040434  0.710663
3  0.110891  0.439337  0.201719  0.895764
4  0.475370  0.563276  0.695516  0.139331
5  0.604417  0.539841  0.203061  0.942854

In [82]:
pd.DataFrame(np.random.randint(0,12,12).reshape(4,3),index=(1,2,3,4),columns=(2,3,4))

2   3   4
1  6  10   2
2  5  11   1
3  9   8   4
4  5  11  11

In [83]:
A =pd.DataFrame(np.random.randn(5,4),index=(1,2,3,4,5),columns=('a','b','c','d'))   # DF thru std normal distribution 
A

a         b         c         d
1 -1.684287 -0.414765 -1.398741 -0.344081
2  0.750786 -0.327625 -0.861598 -0.258185
3  0.460956 -1.349390 -1.019073  0.127012
4 -1.249444  1.945116 -0.153336 -0.906987
5 -0.817354 -0.483123 -0.569828 -2.091600

In [84]:
A.loc[:,'b']   # This returns data frame 
A.loc[4]['c']  # This returns series where we can access series by element or index position
A.loc[4][2]   # This also return same result as above , it access C by position 2

A.iloc[1][1]   # Similar is for iloc , this return series and elemtns can be access by only index position 

-0.3276251832780026

In [85]:
A['a']   # access 1 series/column
A[['a','b']]  # access multiple column 
A['a'][1]   # access element of series by index position 
A.loc[1,['a','b']]   # accessing element by label names usinf loc
A.loc[[1,2,3],['b','c']]   # loc to access multiple rows and multiple column by label name 
A.loc[5,['c','d']]   # using loc and labels 
A.loc[:,'b']
A.loc[1:4,'a':'c']


# A.loc[[1,2],['b','c','d']]
# A.iloc[0:2,1:4]    # using iloc for accessing all elements by row and column using index position

A.iloc[[0,2,4],:]   # this select 1st, 3rd and 5th row and all column 

A.iloc[1:5,0:4]    # using iloc to access row and column by index 
A.iloc[[0,2,3],[0,1,2]]    # using iloc to access multiple rows and multiple columns 



a         b         c
1 -1.684287 -0.414765 -1.398741
3  0.460956 -1.349390 -1.019073
4 -1.249444  1.945116 -0.153336

In [86]:
A['a']

1   -1.684287
2    0.750786
3    0.460956
4   -1.249444
5   -0.817354
Name: a, dtype: float64

In [87]:
A

a         b         c         d
1 -1.684287 -0.414765 -1.398741 -0.344081
2  0.750786 -0.327625 -0.861598 -0.258185
3  0.460956 -1.349390 -1.019073  0.127012
4 -1.249444  1.945116 -0.153336 -0.906987
5 -0.817354 -0.483123 -0.569828 -2.091600

In [88]:
### Logical indexing 
A==1
A[A==1]
A

a         b         c         d
1 -1.684287 -0.414765 -1.398741 -0.344081
2  0.750786 -0.327625 -0.861598 -0.258185
3  0.460956 -1.349390 -1.019073  0.127012
4 -1.249444  1.945116 -0.153336 -0.906987
5 -0.817354 -0.483123 -0.569828 -2.091600

In [89]:
# Adding a new column 
A['e']=np.random.randint(0,15,5)
A

a         b         c         d   e
1 -1.684287 -0.414765 -1.398741 -0.344081  13
2  0.750786 -0.327625 -0.861598 -0.258185   0
3  0.460956 -1.349390 -1.019073  0.127012   9
4 -1.249444  1.945116 -0.153336 -0.906987   3
5 -0.817354 -0.483123 -0.569828 -2.091600  11

In [90]:
# Dropping the column 
A.drop('e',axis=1)  # This drops the column 
A.drop(2,axis=0)    # This drops across the row 



a         b         c         d   e
1 -1.684287 -0.414765 -1.398741 -0.344081  13
3  0.460956 -1.349390 -1.019073  0.127012   9
4 -1.249444  1.945116 -0.153336 -0.906987   3
5 -0.817354 -0.483123 -0.569828 -2.091600  11

In [91]:
# Bot of above dont make the change in original A , so to make change we need to do inplace = True 
A.drop('e',axis=1,inplace=True)
A

a         b         c         d
1 -1.684287 -0.414765 -1.398741 -0.344081
2  0.750786 -0.327625 -0.861598 -0.258185
3  0.460956 -1.349390 -1.019073  0.127012
4 -1.249444  1.945116 -0.153336 -0.906987
5 -0.817354 -0.483123 -0.569828 -2.091600

In [92]:
A.reset_index()   # This reset the index but it still is a function it returns but doesnt make the change , we ned to inplace = True 
A
A.set_index('a').reset_index()   # set index and reset index are bot fnctions but doesnt make changes in original unless we set inplace is true 

a         b         c         d
0 -1.684287 -0.414765 -1.398741 -0.344081
1  0.750786 -0.327625 -0.861598 -0.258185
2  0.460956 -1.349390 -1.019073  0.127012
3 -1.249444  1.945116 -0.153336 -0.906987
4 -0.817354 -0.483123 -0.569828 -2.091600

In [93]:
A

a         b         c         d
1 -1.684287 -0.414765 -1.398741 -0.344081
2  0.750786 -0.327625 -0.861598 -0.258185
3  0.460956 -1.349390 -1.019073  0.127012
4 -1.249444  1.945116 -0.153336 -0.906987
5 -0.817354 -0.483123 -0.569828 -2.091600

In [96]:
A['new']=[i for i in 'Hi how are you there'.split()]
A
A.set_index('new')   # we can set index , create 
# new column , but unless inplace = True , it will not reflect in the original data frame 

a         b         c         d
new                                          
Hi    -1.684287 -0.414765 -1.398741 -0.344081
how    0.750786 -0.327625 -0.861598 -0.258185
are    0.460956 -1.349390 -1.019073  0.127012
you   -1.249444  1.945116 -0.153336 -0.906987
there -0.817354 -0.483123 -0.569828 -2.091600

In [107]:
pd.concat((pd.Series((1,2,3),index=(1,2,3),name='one'),pd.Series((2,3,4))),axis=1)
# concatenation can work on the series , in case index dont match they put Nan values 

# We can do concat on the pandas dataframe 

one    0
0  NaN  2.0
1  1.0  3.0
2  2.0  4.0
3  3.0  NaN

In [112]:
pd.concat((pd.DataFrame({'name':('a','b','c'), 'Age':(20,21,22),'Sex':('M','F','M')}), 
pd.DataFrame({'name':('b','v','p'), 'Age':(22,21,22),'Sex':('M','F','M')})),axis=1)    # concat across the column vertical , concat along rows horizontal

# Here in case index dont match for 2 datframes then it will put Nan Values 

name  Age Sex name  Age Sex
0    a   20   M    b   22   M
1    b   21   F    v   21   F
2    c   22   M    p   22   M

In [136]:
print(pd.concat((pd.DataFrame(np.random.randn(3,3),columns=('a','b','c')) , pd.DataFrame(np.random.rand(3,3),columns=('a','b','c'))),axis=0))   # if columns are same 

print('')

print(pd.concat((pd.DataFrame(np.random.randn(3,3),columns=('a','b','c')) , pd.DataFrame(np.random.rand(3,3),columns=('a','d','c'))),axis=0))  # if columns different , give Nan values 

print('')

print(pd.concat((pd.DataFrame(np.random.randn(3,3),columns=('a','b','c'),index=(1,2,3)) , pd.DataFrame(np.random.rand(3,3),columns=('a','d','c'),index=(2,3,4))),axis=1))    # if column same along columns concat

print('')

print(pd.concat((pd.DataFrame(np.random.randn(3,3),columns=('a','b','c')) , pd.DataFrame(np.random.rand(3,3),columns=('a','d','c'))),axis=1, sort=True))



          a         b         c
0 -0.133401 -0.335785  1.669022
1 -0.259591 -1.503143 -0.245743
2 -0.272724 -2.696887 -0.054295
0  0.914846  0.362394  0.580588
1  0.632264  0.013094  0.663537
2  0.178036  0.961070  0.148663

          a         b         c         d
0 -0.799111 -0.164536  0.000699       NaN
1  0.158256 -0.677566  0.149287       NaN
2 -0.782544  0.674280 -0.114844       NaN
0  0.190688       NaN  0.472067  0.036550
1  0.564841       NaN  0.775528  0.065709
2  0.453289       NaN  0.440763  0.524390

          a         b         c         a         d         c
1  0.155037  1.246085 -2.073390       NaN       NaN       NaN
2 -0.342688 -0.371441 -1.407512  0.025386  0.156153  0.715972
3 -0.777817 -1.110576  1.752270  0.658924  0.027096  0.221972
4       NaN       NaN       NaN  0.231075  0.671893  0.019711

          a         b         c         a         d         c
0  0.098746 -0.130345  0.500478  0.397184  0.668085  0.204984
1 -1.053259 -0.350682 -0.229216  0.293148  0.

#### Axis = 0 will put Nan across the data frame after concat in case column names are different , no impact from different index nos
#### Axis = 1 will put Nan across data frame if index position/nos are different , no impact from different column names 

In [141]:
A =pd.DataFrame(np.random.randn(4,4),columns=(1,2,3,4),index=(1,2,3,4))
B=pd.DataFrame(np.random.rand(4,4),columns=(2,3,4,5),index=(2,3,4,5))
print(A), print(B)

          1         2         3         4
1 -0.096713 -0.539760 -0.778305  0.195845
2 -0.978373  0.408253 -1.702584  1.029156
3  0.472597  0.256030  0.982691  1.665474
4  1.014370 -1.840874 -1.279577 -0.624819
          2         3         4         5
2  0.166283  0.738034  0.082799  0.603152
3  0.245349  0.389296  0.288694  0.355673
4  0.719046  0.297122  0.566405  0.476050
5  0.663671  0.936830  0.732572  0.214940


(None, None)

In [155]:
pd.concat((A,B),axis=0)

pd.concat((A,B),axis=1)

pd.merge(A,B,how='outer',on=2)   # This will outer join union for column 2 , common columns will be name as _x anmd _y 

pd.merge(A,B,how='inner',on=2)    # This will inner join  , common columns will be name as _x anmd _y

pd.merge(A,B,how='left',on=2)     # This will do left join , keep left values , put Nan for right , common columns will be name as _x anmd _y
 
pd.merge(A,B,how='right',on=2)     # This will right join , keep right values put Nan for left , common columns will be name as _x anmd _y

1         2       3_x       4_x  3_y  4_y   5
0 -0.096713 -0.539760 -0.778305  0.195845  NaN  NaN NaN
1 -0.978373  0.408253 -1.702584  1.029156  NaN  NaN NaN
2  0.472597  0.256030  0.982691  1.665474  NaN  NaN NaN
3  1.014370 -1.840874 -1.279577 -0.624819  NaN  NaN NaN

### Merge combine on column values 

### Join combine on index values 

In [158]:
print(A) , print(''), print(B)

          1         2         3         4
1 -0.096713 -0.539760 -0.778305  0.195845
2 -0.978373  0.408253 -1.702584  1.029156
3  0.472597  0.256030  0.982691  1.665474
4  1.014370 -1.840874 -1.279577 -0.624819

          2         3         4         5
2  0.166283  0.738034  0.082799  0.603152
3  0.245349  0.389296  0.288694  0.355673
4  0.719046  0.297122  0.566405  0.476050
5  0.663671  0.936830  0.732572  0.214940


(None, None, None)

In [168]:
A.join(B,how='outer',lsuffix='_left', rsuffix='_right')   # Join works similar to merge except it join on index rather than columns 
#  Use of inner , outer , left and right remains same 

1    2_left    3_left  ...   3_right   4_right         5
1 -0.096713 -0.539760 -0.778305  ...       NaN       NaN       NaN
2 -0.978373  0.408253 -1.702584  ...  0.738034  0.082799  0.603152
3  0.472597  0.256030  0.982691  ...  0.389296  0.288694  0.355673
4  1.014370 -1.840874 -1.279577  ...  0.297122  0.566405  0.476050
5       NaN       NaN       NaN  ...  0.936830  0.732572  0.214940

[5 rows x 8 columns]

### Different Functions for Data frame 

In [183]:
# Unique - works only for series 
A =pd.DataFrame({'A':('one','two','three','four','one'),'B':(1,2,3,4,5),'Sex':('M','F','M','F','M'),'Ed':('G','G','PG','UG','PG')})
A['A'].unique()

# Value count return the count of values in Series 

A['A'].value_counts()


one      2
three    1
four     1
two      1
Name: A, dtype: int64

In [184]:
# Calculate mean 
A.mean()

B    3.0
dtype: float64

In [185]:
# to get columns 
A.columns

Index(['A', 'B', 'Sex', 'Ed'], dtype='object')

In [189]:
A

A  B Sex  Ed
0    one  1   M   G
1    two  2   F   G
2  three  3   M  PG
3   four  4   F  UG
4    one  5   M  PG

In [190]:
A[(A['A']!='one') & (A['Sex']=='F')]   # common filtering on data frames 

A  B Sex  Ed
1   two  2   F   G
3  four  4   F  UG

In [194]:
print(A['B'].mean())

print(A['Sex'].unique())

3.0
['M' 'F']


In [195]:
A

A  B Sex  Ed
0    one  1   M   G
1    two  2   F   G
2  three  3   M  PG
3   four  4   F  UG
4    one  5   M  PG

In [196]:
### Using apply function 

# lambda
# map
# filter
# enumerate
# zip
# apply
# applymap

def profit(s):
  return s*1.2

In [199]:
A['B'].apply(profit)
A

A  B Sex  Ed
0    one  1   M   G
1    two  2   F   G
2  three  3   M  PG
3   four  4   F  UG
4    one  5   M  PG

In [201]:
A['Ed'].apply(len)   # length of series elements 


A      5
B      5
Sex    5
Ed     5
dtype: int64

In [203]:
A.apply(len)   # length of data frame elements by columns 

A      5
B      5
Sex    5
Ed     5
dtype: int64

In [210]:
# In case we want to apply function to more than 1 column 
# we can use apply map function 

A['New']=[1,2,3,4,5]
num =A[['B','New']]     # returns a new data frame with 2 columns having numeric value


In [211]:
# Applymap works only for the data frames 
num.applymap(profit) 
# We apply function profit on 2 columns using applymap

B  New
0  1.2  1.2
1  2.4  2.4
2  3.6  3.6
3  4.8  4.8
4  6.0  6.0

#### Applymap works on data frame return data frame
#### Apply works on series and return series 

In [212]:
A

A  B Sex  Ed  New
0    one  1   M   G    1
1    two  2   F   G    2
2  three  3   M  PG    3
3   four  4   F  UG    4
4    one  5   M  PG    5

In [214]:
def col_sum(i):
  return sum(i)

In [218]:
A[['B','New']].apply(col_sum)

# This function will take each column/series and apply function to return cumulative 


dtype('int64')

In [ ]:
A[['B','New']].applymap(col_sum)

# Applymap works on element by element of data frame and doesnt return cumulative 



#### For Cumulative agtgregation , use Apply which works on series/data frame
#### For element wise aggregation use apply map which works on data frame 

In [225]:
A
A.drop('New', axis=1)   # This drops the element but still original data frame remain same
A

A  B Sex  Ed  New
0    one  1   M   G    1
1    two  2   F   G    2
2  three  3   M  PG    3
3   four  4   F  UG    4
4    one  5   M  PG    5

In [229]:
# to permanent delete the value ..
# either use drop with inplace True or use Del 
del A['New']
A

A  B Sex  Ed
0    one  1   M   G
1    two  2   F   G
2  three  3   M  PG
3   four  4   F  UG
4    one  5   M  PG

In [230]:
# To get the index 

A.index

RangeIndex(start=0, stop=5, step=1)

In [231]:
# to sort the values 

A.sort_values(by='A')

A  B Sex  Ed
3   four  4   F  UG
0    one  1   M   G
4    one  5   M  PG
2  three  3   M  PG
1    two  2   F   G

In [235]:
df=pd.DataFrame({'A':('C1','C1','C2','C2','C3','C3'),'P1':(2,3,6,5,4,5),'P2':(8,9,6,5,4,5)},index=('p1','p2','p3','p4','p5','p6'))
df

A  P1  P2
p1  C1   2   8
p2  C1   3   9
p3  C2   6   6
p4  C2   5   5
p5  C3   4   4
p6  C3   5   5

In [245]:
# Group by is very power ful , once we do group by , we can use other functions
New=df.groupby('A')  
New.describe()

P1                                 ...        P2                           
   count mean       std  min   25%  50%  ...       std  min   25%  50%   75%  max
A                                        ...                                     
C1   2.0  2.5  0.707107  2.0  2.25  2.5  ...  0.707107  8.0  8.25  8.5  8.75  9.0
C2   2.0  5.5  0.707107  5.0  5.25  5.5  ...  0.707107  5.0  5.25  5.5  5.75  6.0
C3   2.0  4.5  0.707107  4.0  4.25  4.5  ...  0.707107  4.0  4.25  4.5  4.75  5.0

[3 rows x 16 columns]

In [241]:
df.groupby('A').mean()

P1   P2
A           
C1  2.5  8.5
C2  5.5  5.5
C3  4.5  4.5

In [240]:
dict={'A':'count','P1':('mean','std'),'P2':('min','max')}

df.groupby('A').agg(dict)    # to calculate other functions using agg method 

A   P1            P2    
   count mean       std min max
A                              
C1     2  2.5  0.707107   8   9
C2     2  5.5  0.707107   5   6
C3     2  4.5  0.707107   4   5

In [246]:
A

A  B Sex  Ed
0    one  1   M   G
1    two  2   F   G
2  three  3   M  PG
3   four  4   F  UG
4    one  5   M  PG

### Saving and loading data frames 

In [249]:
# Saving Data frame to CSV 
A.to_csv('B', index=True)  # This will save index information also 
A


A  B Sex  Ed
0    one  1   M   G
1    two  2   F   G
2  three  3   M  PG
3   four  4   F  UG
4    one  5   M  PG

In [253]:
# Loading Data frame from CSV
pd.read_csv('B',index_col=0)  # here index_col tell that first column is for index

A  B Sex  Ed
0    one  1   M   G
1    two  2   F   G
2  three  3   M  PG
3   four  4   F  UG
4    one  5   M  PG

In [255]:
pd.read_csv('B',index_col='A') 3 using index_col we can put other column as index col_sum



A  Unnamed: 0  B Sex  Ed
0    one           0  1   M   G
1    two           1  2   F   G
2  three           2  3   M  PG
3   four           3  4   F  UG
4    one           4  5   M  PG

In [258]:
# The same above we can do for excel
# in excel everything is same except we need to define the sheet name argument also 
A.to_excel('New.xlsx',index=False,sheet_name='New')

In [261]:
# Loading the excel file
pd.read_excel('New.xlsx',sheet_name='New')   # 

# While loading we need to define the sheet name parameter also 

# also we can define the index col in case we want to set it o something different
pd.read_excel('New.xlsx',sheet_name='New',index_col='Ed') 

A  B Sex
Ed              
G     one  1   M
G     two  2   F
PG  three  3   M
UG   four  4   F
PG    one  5   M