In [1]:
import numpy as np
import pandas as pd

### Numpy basic operations 

In [2]:
np.ones(8)*8

array([8., 8., 8., 8., 8., 8., 8., 8.])

In [3]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [4]:
np.arange(22,31).reshape(3,3)

array([[22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

In [5]:
arr = np.arange(26,51).reshape(5,5)
arr

array([[26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [6]:
arr[2:,1:]

array([[37, 38, 39, 40],
       [42, 43, 44, 45],
       [47, 48, 49, 50]])

In [9]:
arr[4:,4][0]

50

In [18]:
arr

array([[26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [25]:
arr[0:3,1:2]

array([[27],
       [32],
       [37]])

In [26]:
arr

array([[26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [27]:
arr[-1]

array([46, 47, 48, 49, 50])

In [28]:
arr[-2:]

array([[41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [29]:
arr = np.arange(10,40).reshape(6,5)
arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [30]:
arr.sum()

735

In [31]:
np.std(arr)

8.65544144839919

In [32]:
np.mean(arr)

24.5

In [33]:
from google.colab import files
upload_file=files.upload()

Saving sales.csv to sales.csv


In [34]:
df=pd.read_csv('sales.csv')

In [35]:
df.head()

Observation  Dist_Taxi  ...  Daily_Customer_Count  Store_Sales
0            1     9796.0  ...                   530        66490
1            2     8294.0  ...                   210        39820
2            3    11001.0  ...                   720        54010
3            4     8301.0  ...                   620        53730
4            5    10510.0  ...                   450        46620

[5 rows x 10 columns]

In [39]:
df['Parking'].value_counts()

Open            372
Not Provided    227
Covered         188
No Parking      145
Name: Parking, dtype: int64

In [40]:
df['Store_Area'].mean()

1511.862554112554

In [41]:
df.columns

Index(['Observation', 'Dist_Taxi', 'Dist_Market', 'Dist_Metro', 'Store_Area',
       'Items_Available', 'Parking', 'Coupon_Category', 'Daily_Customer_Count',
       'Store_Sales'],
      dtype='object')

In [44]:
df

Observation  Dist_Taxi  ...  Daily_Customer_Count  Store_Sales
0              1     9796.0  ...                   530        66490
1              2     8294.0  ...                   210        39820
2              3    11001.0  ...                   720        54010
3              4     8301.0  ...                   620        53730
4              5    10510.0  ...                   450        46620
..           ...        ...  ...                   ...          ...
927          928    12176.0  ...                  1080        66390
928          929     7214.0  ...                   850        82080
929          930     7423.0  ...                  1060        76440
930          931    15082.0  ...                   770        96610
931          932     9297.0  ...                  1110        54340

[932 rows x 10 columns]

In [45]:
df.loc[2,:]

pandas.core.series.Series

In [48]:
new=df.loc[:,['Coupon_Category','Store_Sales']].head(5)

In [51]:
new.index=['a','b','c','d','e']
new

Coupon_Category  Store_Sales
a           CAT B        66490
b           CAT B        39820
c           CAT A        54010
d           CAT B        53730
e           CAT B        46620

In [52]:
df.loc[((df['Dist_Metro']>18000) &(df['Parking']=='Open')),]

Observation  Dist_Taxi  ...  Daily_Customer_Count  Store_Sales
88            89    14306.0  ...                   330        57860
218          219    11195.0  ...                   480        61660
338          339     9308.0  ...                   430        62710
742          743    12973.0  ...                   680        51380
791          792    14470.0  ...                   900        47300
930          931    15082.0  ...                   770        96610

[6 rows x 10 columns]

In [54]:
df['Store_Sales'].min(), df['Store_Sales'].std()

(300, 50253.6390220453)