In [2]:
import numpy as np 

In [3]:
import torch

In [4]:
torch.__version__

'1.7.0+cu101'

In [5]:
a= torch.tensor(2)
b=torch.tensor(3)
print(a,b)

tensor(2) tensor(3)


In [6]:
print(a+b,a*b,a/b,a**b)

tensor(5) tensor(6) tensor(0.6667) tensor(8)


In [9]:
import numpy as np

In [11]:
a=np.zeros((3,3))
print(a.shape)

(3, 3)


In [12]:
a=torch.zeros((3,3))
print(a.shape)

torch.Size([3, 3])


In [13]:
np.random.seed(42)
a=np.random.randn(4,4)
b=np.random.randn(4,4)
# addition
print(np.add(a,b),'\n')
print(a*b,'\n')
print(np.dot(a,b),'\n')

[[-0.51611697  0.17598303 -0.26033554  0.11072616]
 [ 1.23149539 -0.45991326  1.64674102 -0.65731346]
 [-1.01385711  0.65348263 -1.61441127 -0.09003174]
 [-0.35867642 -2.20497399 -2.32662444  1.28999066]] 

[[-0.50308755 -0.04344919 -0.58811679 -2.1509807 ]
 [-0.34318661  0.05286258  0.10664141 -1.09340124]
 [ 0.25557375  0.06018217  0.53339079 -0.17497375]
 [-0.1453319   0.55809189  1.03789447 -1.04151292]] 

[[-1.97311556 -0.1851071  -2.12226763  2.55989085]
 [-1.42665188 -0.06940504 -2.08262831  2.67909161]
 [ 1.80271262 -0.18558131  1.27655561 -1.1467372 ]
 [-1.77251664  0.48069274  1.97479352  0.69465721]] 



In [17]:
print(a,'\n')
print(b)

[[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783 -0.56228753]] 

[[-1.01283112  0.31424733 -0.90802408 -1.4123037 ]
 [ 1.46564877 -0.2257763   0.0675282  -1.42474819]
 [-0.54438272  0.11092259 -1.15099358  0.37569802]
 [-0.60063869 -0.29169375 -0.60170661  1.85227818]]
